rule (js/react) - format zdjęć
ec0lint/ec0lint pull request #22
Opened 2022-08-26 18:32 UTC by martinabab

#### Pull Request purpose

[ ] Documentation update
[ ] Bug fix
[x] New rule
[ ] Updates an existing rule
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### Checklist

[ ] Update CHANGELOG.md
[ ] (if rule) Docs added (/docs/rules/<rule_name>)

#### Overview of changes

#### Would you like to add anything more?

2022-08-27 12:11 UTC, malwinq requested changes
overall looks great, let's update the comments I added and then let @nemmip give final review

2022-08-27 12:11 UTC, malwinq commented on lib/rules/index.js
> +    "lighter-image-react": () => require("./lighter-image-react")
can we please rename to ligher-image-file? So we'll be consistent across ec0lint and ec0lint-style

2022-08-27 12:11 UTC, malwinq commented on lib/rules/lighter-image-react.js
> +            url: ""
I think the url needs to be added here - with wrong eslint reference: https://eslint.org/docs/rules/<rule_name>
It will be fixed in next PR

2022-08-27 12:11 UTC, malwinq commented on lib/rules/lighter-image-react.js
> +          suggestion: "Format of image file can be changed to WebP, SVG, GIF or JPG. CO2 reduction: up to 99% of the image file."
can we please change it to the same error log as in ec0lint-style? https://github.com/ec0lint/ec0lint-style/blob/main/lib/rules/lighter-image-files/index.js

2022-08-27 15:55 UTC, malwinq requested changes, later dismissed

2022-08-27 15:55 UTC, malwinq commented on lib/rules/lighter-image-file.js
> +            url: "https://eslint.org/docs/rules/lighter-image-react"
this needs to be changed to 'image'

2022-08-27 15:55 UTC, malwinq commented on lib/rules/index.js
> +    "lighter-image-file": () => require("./lighter-image-react")
it causes test failures

2022-08-31 17:17 UTC, nemmip reviewed
overall lgtm just look at these improovements

2022-08-31 17:17 UTC, nemmip commented on lib/rules/lighter-image-file.js
> +        const options = {};
why do you declare empty object if it's not really used

2022-08-31 17:17 UTC, nemmip commented on lib/rules/lighter-image-file.js
> +        const allowed = options.allow || [];
you can also delete this also, bc you don't use it in this scope

2022-08-31 17:17 UTC, nemmip commented on lib/rules/lighter-image-file.js
> +            if (allowed.indexOf(name) === -1 && isBanned(name)) {
i don't get it - at first, you declare an empty object of options (there aren't given by argument), then you try to get an `allow` attribute from an empty object or declare an empty array and finally here, you are looking for smth in this array.  Imo if you want to use options in the future just pass them as argument into the rule. If you just want to ban some specific image extensions just declare this array if it will be actually used. If not I would just throw it, add optional TODO and just stay with `isBanned` function

2022-08-31 17:17 UTC, nemmip commented on tests/lib/rules/lighter-image-file.js
> +//npm run test:cli tests/lib/rules/lighter-image-file.js
comment to remove

2022-11-01 19:42 UTC, malwinq approved these changes
ready to merge

2022-11-01 19:48 UTC, merged